### ISSUE TITLE
Apache Client HTTP Library Deprecated

### ISSUE THREAD

**Issue by zerox1212** [dreamfactorysoftware/android-sdk#10]
Android API 23 has deprecated Apache client HTTP library. HTTP client should be replaced with HttpURLConnection. Unfortunately it might be a big change and not implemented for a while, but I figured I should make it an issue. That way other people who are reading this that try to implement the DF android SDK in Android 6.0 (API 23) know why gradle complains.

**Comment by tmrtrn** [comment]
Do you think to update the library or is there any way to get around to solve the issue?

**Comment by zerox1212** [comment]
As a follow up to this.

Has anyone looked at migrating this SDK to use the AOSP Volley library? Seems like it would really clean up the code, improve functionality (you get queues and retries out of the box), and user code no longer needs boiler-plate http client.

https://developer.android.com/training/volley/index.html

**Comment by zerox1212** [comment]
I just realized the SDK has been refactored using Retrofit2, which is great. Thanks for the hard work.
