### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by zerox1212** [dreamfactorysoftware/android-sdk#13]
Does the DF API code support SSL? Are there any docs on DF Andoid SDK security?

The API should probably have some notes about SSL because the app is sending user passwords...
Especially because it's quite easy to support SSL on the bitnami image.

**Comment by HavardLine** [comment]
Hi @zerox1212 ,

YES, an application in the wild should have TLS (previusly known as SSL). For security, privacy and preventing data corruption.

As far as I understand you have to have a TLS proxy. I think it is mentioned in [this](https://twit.tv/shows/floss-weekly/episodes/391) podcast.

We have implemented NGINX as a TLS proxy for Dreamfactory. You can find our obscure deployment-code [here](https://github.com/LTS-AS/CoreOS).
