### ISSUE TITLE
Sorry newbie question

### ISSUE THREAD

**Issue by jackandjill** [dreamfactorysoftware/android-sdk#7]
Tried importing the project in to eclipse.
But I think it is not importing the .java files from the src folder. Please assist on how to. 
It would be a great help for everyone if you could just upload the Android Studio version as it is the official IDE for Android moving forward. Tks

**Comment by at-dev** [comment]
Try these steps 
Add SDK source code as external source. Go to Project Properties > Java Build Path > Source tab > add external SDK folder, this should resolve errors. Hope this will help. Let me know if does have any issues.

**Comment by jackandjill** [comment]
I think may be a picture of what I am facing the issue might help, cause I think you might be referring to the src folder in the SampleApp folder.
![image](https://cloud.githubusercontent.com/assets/7009140/6425425/3ed42924-bf63-11e4-8473-7f3df71fd279.png)

Btw, tks for responding so fast.

**Comment by jackandjill** [comment]
Oh nvm, got it resolved. Now will try to export and import to Android Studio. Tks

**Comment by at-dev** [comment]
Great.. Post if any issues or questions on using sdk.
