### ISSUE TITLE
Problems after migrating to gradle

### ISSUE THREAD

**Issue by jackandjill** [dreamfactorysoftware/android-sdk#8]
Hi,
After I managed to overcome the previous issue of not able to add the src folder, now I face a similar issue. The issue is this.
After I export the project from eclipse, this is to migrate to gradle from ant (as the current project is in Github), I am having hard time getting the src folder to be imported to the project even though I sucessfully managed to import in to android studio and utilizing gradle now.

**Comment by at-dev** [comment]
What is exactly issue that you are facing? I'm sure you've already tried but i'll suggest try to add src folder as external src path or if still does not works you can also include src into your main project folder, and here we can create a sample script to show how to get project compiled with gradle.

**Comment by jackandjill** [comment]
Hi, yes you are right. I have tried that, BUT the issue is the import is not working as it should be in Android Studio. Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/7009140/6550010/e7135cf8-c658-11e4-9b8c-eae80b3e559d.png)

What I am thinking is that we have to do some code change in gradle.build? Please let me know if that is the required change, here is the screenshot of the directory added.
![image](https://cloud.githubusercontent.com/assets/7009140/6550030/51a016b0-c659-11e4-8dbe-630f96137002.png)

**Comment by at-dev** [comment]
I've not tried it on android studio but from above screenshot a quick try is: cut and paste dreamfactory folder into your src folder, and it should work.

**Comment by jackandjill** [comment]
Yes, that worked!
BUT, then I started to have these issues

http://stackoverflow.com/questions/20827885/android-studio-0-4-duplicate-files-copied-in-apk-meta-inf-license-txt

 and to resolve them your build.gradle file should some what like this...

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.0'
    }
}
apply plugin: 'android'

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
}

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src','srcDf','sdk']
            resources.srcDirs = ['src','srcDf','sdk']
            aidl.srcDirs = ['src','srcDf','sdk']
            renderscript.srcDirs = ['src','srcDf','sdk']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']

        }

        // Move the tests to tests/java, tests/res, etc...
        instrumentTest.setRoot('tests')

        // Move the build types to build-types/<type>
        // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
        // This moves them out of them default location under src/<type>/... which would
        // conflict with src/ being used by the main source set.
        // Adding new build types or product flavors should be accompanied
        // by a similar customization.
        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }


    packagingOptions {

        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE.txt'
    }
}


One more question, this is really not an issue.. what is the link I have to put in the DSP URL?
This is my dsp
https://dsp-bharath-dsp.cloud.dreamfactory.com/
But I tried other links and my login to the dsp but unable to login, appreciate yourhelp.

**Comment by jackandjill** [comment]
Hi,
Any update on the dsp link that I have to put in? tks

**Comment by at-dev** [comment]
try adding /rest at end of url or debug what is the error exactly it throwing.

**Comment by jackandjill** [comment]
It is not throwing any error, actually.. this is the screenshot.. actually i tired /rest no resolution
then I tried this URL
https://dsp-bharath-dsp.cloud.dreamfactory.com/applications/todojquery/index.html
![image](https://cloud.githubusercontent.com/assets/7009140/6569113/e90dff74-c71e-11e4-8d4c-01e428dcf326.png)

**Comment by alokt** [comment]
U souls try to debug it

Thanks,
-Alok

**Comment by jackandjill** [comment]
I was looking at the logcat and I dont really find anything other than this

![image](https://cloud.githubusercontent.com/assets/7009140/6569236/52a74b64-c721-11e4-89c4-3441888e8e31.png)

**Comment by jackandjill** [comment]
But what do u guys usually use? i mean since you have used it before and it was working for you.

**Comment by alokt** [comment]
we use eclipse.

**Comment by jackandjill** [comment]
so in eclipse what is the url that u guys input?
