### ISSUE TITLE
User Register Improvements

### ISSUE THREAD

**Issue by zerox1212** [dreamfactorysoftware/android-sdk#9]
The RegisterTask doesn't handle passwords that are too short. The DF REST API requires a minimum of 6 characters in the password (oddly you can break this rule from the DF Admin Console, bug?).

Should this be checked directly in the Android text field? Or should the DF API throw an exception that the password is too short?

Another small note. If you don't set the DF instance user service: Open Reg Email to blank, the "login" queryParams won't actually work because confirmation is required.

**Comment by todda48** [comment]
Ideally both app and server should validate the password. I have logged an issue for the server side. We might make the min length configurable. Once all that is working we can update the sample apps to do their own validation.

The open reg behavior you saw is expected, needs improvement.
